apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: test
  labels:
    app: my-nginx
spec:
  selector:
    app: my-nginx
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  type: NodePort
